### ISSUE TITLE
Implement friends-of-friends algorithm to generate blends

### ISSUE THREAD

**Issue by sowmyakth** [LSSTDESC/BlendingToolKit#16]
Extension of #4 to implement friends-of-friend algorithm in creating blend_list in `create_blend_generator`. Currently realistic blends can only be created by identifying groups in a pre-run WLD catalog as shown in notebooks/custom_sampling_function.ipynb shows. A fast on the fly identification of neighbors in a group would eliminate to run the WLD catalog beforehand.

**Comment by ismael2395** [comment]
Hi @sowmyakth , I like this idea, could you elaborate a bit on what it involves or where you thinking of incorporating this FOF algorithm for the blends?

**Comment by sowmyakth** [comment]
@ismael2395 I was thinking an extension of example 4 in this [notebook](https://github.com/LSSTDESC/BlendingToolKit/blob/9e4f0d5fa175592ebd646e433fbc87bcdf9a0d46/notebooks/custom_sampling_function.ipynb). Here galaxies within a certain threshold radius of a central galaxy are classified as part of the blend. It would be nice to also recursively include galaxies within the threshold radius of all those selected galaxies to also be included in the blend. At least that's the idea. @cosmicshear who has implemented this in his unrecognized blends study may have additional input.

**Comment by ismael2395** [comment]
See also this notebook: https://github.com/LSSTDESC/DC2-analysis/blob/master/tutorials/matching_fof.ipynb

**Comment by enourbakhsh** [comment]
@cosmicshear here (renamed my GitHub recently). In case you are interested in using FoF, I made a parallel python package similar in use to `FoFCatalogMatching` which runs >1 order of magnitude faster. Planning on uploading it to PyPI after adding some docstrings.

**Comment by fjaviersanchez** [comment]
@ismael2395, I leave this info here for your consideration too. Please feel free to disregard if it's not useful. I found that `sklearn.neighbors.KDTree` works much faster than `FoFCatalogMatching` if you just want to query neighbors within a certain radius: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KDTree.html (I would build a tree with the centroids of the objects themselves and just `query_radius`with the `counts_only = True` option, and check if the returned number is larger than 1 to focus on those, for the radius you can play a bit since it will depend on the FWHM that you use for the images).

**Comment by enourbakhsh** [comment]
@ismael2395, my fast FoF code, [SkyLink](https://github.com/enourbakhsh/SkyLink), is now on Github. It needs some cleanups here and there but it works. I think with some modifications, it can be used to address this issue.

**Comment by ismael2395** [comment]
Thanks @enourbakhsh and @fjaviersanchez for your suggestions!

**Comment by ismael-mendoza** [comment]
Closed in #460
