### ISSUE TITLE
Custom PSF feature leads to abnormal images

### ISSUE THREAD

**Issue by mpaillassa** [LSSTDESC/BlendingToolKit#208]
I am regularly simulating HSC images using the COSMOS galaxies and the custom PSF feature and I recently got some issues with the later.

Since the merging of #187, I get abnormal images when using a custom PSF: images (especially in the g, r and i HSC bands) contain very high pixel values (~1e19 in the sky background up to 1e28 in source peaks). I get no issues when using analytic PSFs and in both cases the output PSF images look good.

I checked back simulations of the same galaxies with the same custom PSFs using BTK code before merging of #187 and all is fine, so one change in this PR should be the cause of the issue but I cannot see what modification from #187 could impact the custom PSF feature...

**Comment by ismael-mendoza** [comment]
Hi @mpaillassa thanks for point this issue out! I have a couple of questions which will lead us to the bug and if you could help out with this we would really appreciate it!

(1) Are you sure these issues with the custom PSF arise due to the changes in #187? Just to be sure (assuming you haven't done this), could you revert to the commit right before and after #187 and confirm ? 
(2) I scanned briefly through this PR and maybe it would be good to double-check the survey values for HSC ? Particularly the zero_points that @thuiop calculated ? 
(3) Confirm that the way @thuiop changed the equation to calculate fluxes is correct
```
mag = ab_magnitude + filt.extinction * (survey.airmass - survey.zeropoint_airmass)
return filt.exp_time * 10 ** (-0.4 * (mag - filt.zeropoint))
```
vs before
```
mag = ab_magnitude + filt.extinction * (survey.airmass - survey.zeropoint_airmass)
return filt.exp_time * filt.zeropoint * 10 ** (-0.4 * (mag - 24))
```
(4) 
> output PSF images look good.

Here you are referring to the custom PSF right? Not the analytical? Are the PSF images the same before #187 and after? 

I'm happy to discuss this during the meeting on Wed if you have time to this before then (either way is ok ). I think question (1) would be particularly telling at pointing us in the right direction to find the bug.

**Comment by mpaillassa** [comment]
Hello, thank you for getting into this. I double checked more carefully and all is fine in BTK, the mistake was on my side ! Sorry for this. I close the issue.

**Comment by ismael-mendoza** [comment]
Thanks for looking into this @mpaillassa ! I'm glad you figure out the issue
