### ISSUE TITLE
add wcs (part 1) 

### ISSUE THREAD

**Issue by ismael2395** [LSSTDESC/BlendingToolKit#40]
As discussed with @herjy and @thuiop we will start working towards adding multi-resolution capabilities in BTK, a first step is to enable WCS compatibility in single resolution images. 

A small change to get us started is to add WCS information using the [code](https://github.com/herjy/Multi_resolution_comparison/blob/master/mr_tools/mr_tools/galsim_compare_tools.py) from @herjy into the output dictionary of the `draw_blend_generator`. 

Here are the steps from what I can see: 

- [ ] Add code to create wcs information in `create_observing_generator.py` 

- [ ] You can use the galsim image in this [line](https://github.com/LSSTDESC/BlendingToolKit/blob/d7ab514770eb09d27770a0a07a71877902536f23/btk/draw_blends.py#L137) to get the `true_center` which seems to be required to run `mk_wcs`(see [line](https://github.com/herjy/Multi_resolution_comparison/blob/f153c4ed97709935faca444d9ddc7972e75aa7c4/mr_tools/mr_tools/galsim_compare_tools.py#L160)). 

- [ ] You can store the `wcs` information for each galaxy in the blend in a list that you return in `run_single_band`, `run_mini_batch` and then as part of the dictionary of `generate` (all these functions are in [draw_blends.py](https://github.com/LSSTDESC/BlendingToolKit/blob/master/btk/draw_blends.py#L137)). 

@thuiop can you open a PR to address this github issue? It would be great if @herjy can review this PR alongside me. 

@thuiop feel free to add more comments to this github issue if you have any questions or encounter any problems along the way.

**Comment by thuiop** [comment]
I added a "basic" WCS feature, where the WCS is instanciated in the run_mini_batch, using as an origin the center of the image (in pixels) and (0,0) in sky coordinates. I have tested it by successfully computing dx and dy from ra and dec for some of the galaxies. I do not think there is any need to store additionnal data for galaxies as long as we have the sky coordinates.

The question that arises is how much customization is needed. Right now, I use default parameters for everything. Would it be useful to allow the users to choose the reference coordinates in pixels and in sky coordinates ? To chose the type of projection ? Maybe @herjy has some useful input on what is needed.
If so, the observing_generator seems to be a good place for this kind of input ;  the issue is that it currently returns a descwl survey object which does not have fields for this kind of information so we will need to change the output format (it is doable, but changes a significant portion of the code).

Another minor issue : the astropy wcs methods wcs_world2pix and wcs_pix2world are *supposed* to use degrees for the sky coordinates instead of arcseconds. Right now I have set them to use arcseconds for test purposes but users might be confused and expect degrees if they look at the astropy documentation. Should I switch it to degrees ?

**Comment by ismael2395** [comment]
Thanks @thuiop for your discussion questions, 

> I added a "basic" WCS feature, where the WCS is instanciated in the run_mini_batch, using as an origin the center of the image (in pixels) and (0,0) in sky coordinates. I have tested it by successfully computing dx and dy from ra and dec for some of the galaxies. I do not think there is any need to store additionnal data for galaxies as long as we have the sky coordinates.

Great! thanks for testing this. Later on (once we add more WCS code) we can think of adding a small unit test to make sure the wcs code does not break. 

> The question that arises is how much customization is needed. Right now, I use default parameters for everything. Would it be useful to allow the users to choose the reference coordinates in pixels and in sky coordinates ? To chose the type of projection ? Maybe @herjy has some useful input on what is needed.

Indeed @herjy input on this would great. 

> If so, the observing_generator seems to be a good place for this kind of input ; the issue is that it currently returns a descwl survey object which does not have fields for this kind of information so we will need to change the output format (it is doable, but changes a significant portion of the code).

Yeah that's right, depending on @herjy's input we can think of adding more information to the observing generator by making it a dictionary or something like that. I agree it would change many parts of the code though. 

> Another minor issue : the astropy wcs methods wcs_world2pix and wcs_pix2world are supposed to use degrees for the sky coordinates instead of arcseconds. Right now I have set them to use arcseconds for test purposes but users might be confused and expect degrees if they look at the astropy documentation. Should I switch it to degrees ?

I like keeping everything in arcseconds for consistency, is there a way to make your choice explicit in the code? ( I don't see it)

**Comment by herjy** [comment]
I think the `observing_generator` should return an object of its own, possibly one that could inherit from `descwl survey` objects. Indeed, allowing for custom wcs coordinates and transform would be nice. Right now I just put a default coordinate in there. If we think about making simulations that matches other large scale runs, say DC2, it could come very handy to have that in place.

**Comment by thuiop** [comment]
I created a custom survey class for that purpose ; you can now input your center_pix and center_sky value through the observing_generator. Would it be useful to allow for different types of projections ? Right now there is only the default `"RA---AIR", "DEC--AIR"` as ctype, but if needed I can easily make it a additionnal parameter for the user (also, is AIR the best as a default projection ?).

**Comment by jmeyers314** [comment]
>(also, is AIR the best as a default projection ?).

I'd recommend gnomonic projection.  I.e., "RA---TAN", "DEC--TAN".  This projection seems to be the most common out in the wild.
