### ISSUE TITLE
LSST survey import

### ISSUE THREAD

**Issue by SampsonML** [LSSTDESC/BlendingToolKit#417]
Hi, I am trying to run the BTK notebooks, to create a mock catalog of galaxy blends but when I run `LSST = btk.survey.get_surveys("LSST")` 

I get issues of 
`[/Users/mattsampson/miniconda3/envs/blender3/lib/python3.8/site-packages/btk/survey.py:128](https://file+.vscode-resource.vscode-cdn.net/Users/mattsampson/miniconda3/envs/blender3/lib/python3.8/site-packages/btk/survey.py:128): UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  with initialize(config_path=".[./conf](https://file+.vscode-resource.vscode-cdn.net/Users/mattsampson/Princeton/SampsonMelchior/software/BlendingMockGals/conf)"):
[/Users/mattsampson/miniconda3/envs/blender3/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251](https://file+.vscode-resource.vscode-cdn.net/Users/mattsampson/miniconda3/envs/blender3/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251): UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)`
  
Is this due to my specific hydra package? The documentation does not seem to specify any versions of required packages, however I found there to be some specific requirements as some such as markupsafe have breaking issues.

Also, the stable pip installed version of BTK seems to be different to the version from  used in the notebooks, as I can see `DEFAULT_SEED = 0` is removed from the `__init__.py` in the stable 0.9.3 version

**Comment by ismael-mendoza** [comment]
Hi @SampsonML thanks for opening an issue - 

That's an interesting error to get as we don't use hydra anymore. Could you try installing directly from the main branch? 

```
pip install git+https://github.com/LSSTDESC/BlendingToolKit.git
```

Alternatively, could you try installing the latest pre-release branch? 

```
pip install blending-toolkit==1.0.0a9
```

And see if you get the same error? The latest stable version `0.9.3` is pretty old. We switched to doing pre-releases as we were getting close to v1.0.0 but I understand it's confusing since they are not stable versions. 

Please let me know if you encounter any other bugs and I'm happy to help!

**Comment by SampsonML** [comment]
Hi, thanks for the help. 

Installing the latest pre-release version indeed works, cheers.

**Comment by ismael-mendoza** [comment]
Excellent, please feel free to reopen this issue if anything comes up
