### ISSUE TITLE
Simplify the user interface

### ISSUE THREAD

**Issue by herjy** [LSSTDESC/BlendingToolKit#74]
At the moment the user interface seems somewhat heavy. A user has to define a `BlendGenerator`, an `ObservingGenerator`, a `DrawBlendGenerator`, which all have pretty similar names and pipe into each other. And this is on top of the `catalog`, `sampling_functions`, `Cutout` and `obs_conditions`. This makes a LOT of objects which role I am not completely clear about. At the very least, we should come up with better, much more explicit names for these. While I understand that these classes give us some flexibility and allow the user for quick coding of custom classes I am convinced that this can be simplified. 

In an upcoming PR, I propose to rethink the name of these classes at the very least and to think of ways of simplifying the API.

**Comment by thuiop** [comment]
My take on this is that : 
- The BlendGenerator and the ObservingGenerator should be hidden in the DrawBlendsGenerator (which definitely should be renamed) ; I guess they could be instantiated in the __init__. Users would provide the sampling function and the obs conditions to this unique generator and get away with it, instead of providing them to the BlendGenerator and the ObservingGenerator and then give those to the DrawBlendsGenerator.
- Similar modifications could be made to the MeasureGenerator ; this may require some thinking over, as currently the MeasureGenerator should work either with WLD or with COSMOS, without needing to modify it.
- The duo ObsConditions-Cutout is definitely the thing I find the most confusing at the moment. I believe there should be a way to combine them into a single object, probably by "absorbing" the cutout into the obs_conditions. I can see two reasons why they are separated : first, there is one cutout per band (for each survey), and we would not want users to manually setup 6+ cutouts ; they can work with ObsConditions instead to build all the cutouts from the data they already have. Secondly, the cutouts are originally built on descwl Survey object, and in the case of WLD they inherit directly from its structure, which allows them to be fed directly to WLD when rendering.

I believe that if we can adress those issues, we would get a much clearer workflow : the user defines a sampling function (exactly as of now) and observing conditions (using the new object), gives them to the generator and get the results. I feel the measure part is in an okay place right now. We would however need to clarify the metrics part but this will come in later I guess.

**Comment by thuiop** [comment]
A quick idea that I had, which may need some thinking about after the break : we talked a bit about the possibility of having a "Filter" object as a part of the Surveys objects ; those would look a lot like the cutouts. Should we forego the cutouts and the obs_conditions entirely and have everything being provided as a Survey with some Filters ? We could maybe keep the Cutouts internally, and they could be directly constructed for each filter (keeping some features like generating the psf image and so on).

**Comment by ismael-mendoza** [comment]
I think we resolved this issue in #85  and #87. Thanks everyone!
