### ISSUE TITLE
Add functionality for realistic PSF

### ISSUE THREAD

**Issue by HironaoMiyatake** [LSSTDESC/BlendingToolKit#76]
We want to add a functionality to import realistic PSF.  We should first brainstorm how to implement this. I think we can start with the following points.
- Format: The most flexible format would be an image. We may also want a capability to talk to the DM stack directly. We could add a capability to specify which `GalSim` PSF to use, since `GalSim` also has realistic PSFs such as the Kolmogorov profile and Zernike aberration model.
- We have subclasses of `Cutout` for WLD and COSMOS real images. Should we separately implement the realistic PSF capability for these subclasses, or can we share it among subclasses? I am not familiar with WLD, but it also uses galsim, so it might be possible to go with the latter.

**Comment by thuiop** [comment]
WLD takes as input a bunch of parameters corresponding to the instrument and the atmosphere and generate a PSF based on those (see their Survey class for more details) ; I do not think they support providing a custom PSF.

**Comment by HironaoMiyatake** [comment]
We might not need a realistic PSF for parametric galaxy models, but if we want adding such a functionality to WLD is out of our scope?

**Comment by thuiop** [comment]
For now we have considered that modifying WLD for BTK purposes was out of scope ; I suppose it could be discussed (although their PSF modeling is pretty complete, even if you cannot provide a custom PSF as an image for example).

Another issue I thought about : if you are dealing with more realistic PSF, you might want to get a different one for images within the same batch ? Currently we have the same observing conditions on the whole batch.

**Comment by HironaoMiyatake** [comment]
Ismael and I plan to have a telecon dedicated for this issue after the big PR is done, so we should discuss the first point then.

I should also discuss about the second point in the telecon. It would be also nice to have such a flexibility, but I do not think it's urgent. If we want to add this flexibility, maybe we want to do the same for the sky level.

**Comment by thuiop** [comment]
Following the massive changes from PR #87, we should talk a bit more about how to integrate the PSF into btk. In this PR, the PSF is managed by the `get_psf` function which is called in the DrawBlendsGenerator, which returns a list of PSF models (one for each filter). I find this unpractical, as there is no way to override this function and get a custom PSF ; also, the PSF would be the same for COSMOS and Catsim (though it is not necessarily an issue). @aboucaud also pointed out that the get_psf should at least return only one PSF given a filter, instead of a list of PSF with a survey. The possibilities I see :
- Making the get_psf a method of the DrawBlendsGenerator ; users can have a custom PSF by writing there own DrawBlendsGenerator
- Making the get_psf an argument for initializing the DrawBlendsGenerator (does not feel very satisfying to me but it should work)
- my preference : making the PSF one of the attributes of the Filter object. It could be provided as a Galsim model, or a file (or an image ?. I think this is the most flexible.

@HironaoMiyatake @mpaillassa Which one do you think makes the more sense ? Or do you have an other proposal ?

**Comment by mpaillassa** [comment]
I do not have a very clear view of all the changes from PR #87 yet but I think you preferred solution would be nice for BTK, especially if it is the most flexible. So the plan would be to implement it after the merging of PR #87 or within it ?

**Comment by HironaoMiyatake** [comment]
I guess the third option is most user-friendly. For now, having a single PSF for a filter would be okay, but in the future we might want multiple PSFs per filter and randomly draw a PSF to make the simulation more complicated. This can be anyway implemented later.

**Comment by thuiop** [comment]
I do not think multiple PSF will be an issue ; I agree that we can implement it later if we want to keep small PRs.
And the plan is to merge #87, and then do a new PR to setup the new PSF system.

**Comment by HironaoMiyatake** [comment]
Sounds good!
